// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:80295b80-0919-489e-b2ca-968e0f414844",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_80ti0u6Nc",
    "aws_user_pools_web_client_id": "11qsqvcn83n6jhpfmo6tqvl4gp",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://745j4tuopvhrremh5nsiwzlbzy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
